/**
 * One health-check probe result. High-volume collection: ~70 endpoints x 288
 * checks/day = ~20k docs/day, so raw results expire via TTL index after
 * CHECK_RETENTION_DAYS. Long-term statistics are preserved in DailyUptime.
 */
const mongoose = require('mongoose');
const config = require('../config');

const checkResultSchema = new mongoose.Schema(
  {
    service: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'ServiceEndpoint',
      required: true,
      index: true,
    },
    checkedAt: { type: Date, default: Date.now },
    ok: { type: Boolean, required: true },
    httpStatus: { type: Number },
    latencyMs: { type: Number },
    error: { type: String, default: '' },
    // 'live' = real HTTP probe, 'simulated' = SIMULATE_CHECKS demo mode,
    // 'seeded' = generated by seed scripts for historical demo data.
    mode: { type: String, enum: ['live', 'simulated', 'seeded'], default: 'live' },
  },
  { versionKey: false }
);

checkResultSchema.index({ service: 1, checkedAt: -1 });
// TTL cleanup of raw checks (no-op on engines without TTL support; the
// scheduler also prunes explicitly once a day as a portable fallback).
checkResultSchema.index(
  { checkedAt: 1 },
  { expireAfterSeconds: config.monitor.retentionDays * 86400 }
);

module.exports = mongoose.model('CheckResult', checkResultSchema);
